import assert from "node:assert/strict";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { parse as parseYaml } from "yaml";

import {
  inspectArchitecture,
  readScaffoldProfile,
  verifyScaffoldProfile,
} from "../architectures/nextjs-gcp-postgres/repo-overlay/scripts/architecture/nextjs-gcp-postgres/verify.mjs";
import {
  configureScaffold,
  loadScaffoldBaseline,
} from "../architectures/nextjs-gcp-postgres/configure-scaffold.mjs";
import { writeScaffold } from "./helpers/fixture.mjs";

test("applies the exact Mantine baseline and removes Tailwind", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-mantine-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    const docsPackagePath = join(root, "apps/docs/package.json");
    const docsPackageBefore = JSON.parse(readFileSync(docsPackagePath, "utf8"));
    docsPackageBefore.dependencies["@repo/ui"] = "*";
    writeFileSync(
      docsPackagePath,
      `${JSON.stringify(docsPackageBefore, null, 2)}\n`,
    );
    const baseline = loadScaffoldBaseline();
    const profile = configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const webPackage = JSON.parse(
      readFileSync(join(root, "apps/web/package.json"), "utf8"),
    );
    const uiPackage = JSON.parse(
      readFileSync(join(root, "packages/ui/package.json"), "utf8"),
    );
    const rootPackage = JSON.parse(
      readFileSync(join(root, "package.json"), "utf8"),
    );
    const eslintPackage = JSON.parse(
      readFileSync(join(root, "packages/eslint-config/package.json"), "utf8"),
    );
    const readme = readFileSync(join(root, "README.md"), "utf8");

    assert.equal(profile.framework.version, baseline.dependencies.next);
    assert.equal(profile.ui.version, baseline.dependencies["@mantine/core"]);
    assert.equal(profile.schemaVersion, 4);
    assert.equal(profile.dataLayer, "postgres");
    assert.deepEqual(profile.node, baseline.parallelSlices.node);
    assert.deepEqual(profile.applications, ["apps/web"]);
    assert.equal(existsSync(join(root, "apps/docs")), false);
    assert.equal(webPackage.dependencies.react, baseline.dependencies.react);
    assert.equal(docsPackageBefore.dependencies["@repo/ui"], "*");
    assert.equal(
      webPackage.devDependencies["postcss-preset-mantine"],
      baseline.devDependencies["postcss-preset-mantine"],
    );
    assert.equal(uiPackage.dependencies["@mantine/core"], profile.ui.version);
    assert.equal(
      rootPackage.packageManager,
      `npm@${baseline.parallelSlices.packageManagers.npm}`,
    );
    assert.deepEqual(profile.review, { cursorProvider: "cursor-agent" });
    assert.equal(rootPackage.devDependencies["@cursor/sdk"], undefined);
    assert.equal(
      rootPackage.engines.node,
      baseline.parallelSlices.node.engines,
    );
    assert.equal(
      readFileSync(join(root, ".node-version"), "utf8"),
      `${baseline.parallelSlices.node.pin}\n`,
    );
    for (const name of ["husky", "prettier", "turbo", "typescript"]) {
      assert.equal(
        rootPackage.devDependencies[name],
        baseline.devDependencies[name],
      );
    }
    for (const name of [
      "@eslint/js",
      "eslint",
      "eslint-config-prettier",
      "eslint-plugin-only-warn",
      "eslint-plugin-react",
      "eslint-plugin-react-hooks",
      "eslint-plugin-turbo",
      "globals",
      "typescript-eslint",
    ]) {
      assert.equal(
        eslintPackage.devDependencies[name],
        baseline.devDependencies[name],
      );
    }
    assert.equal(
      rootPackage.overrides.postcss,
      baseline.devDependencies.postcss,
    );
    assert.doesNotMatch(
      readFileSync(join(root, "apps/web/app/globals.css"), "utf8"),
      /tailwind/i,
    );
    assert.match(readme, /Default controller: `Cursor`/);
    assert.match(readme, /Architecture: `nextjs-gcp-postgres`/);
    assert.match(readme, /\.parallel-slices\/architecture\.json/);
    assert.match(readme, /This starter project was generated by/);
    assert.match(
      readme,
      /github\.com\/jtrefry\/parallel-slices\/blob\/main\/docs\/mechanism-map\.md/,
    );
    assert.match(
      readme,
      /github\.com\/jtrefry\/parallel-slices\/blob\/main\/docs\/pipeline-walkthrough\.md/,
    );
    assert.match(readme, /docs\/parallel-slices\/using-codex\.md/);
    assert.match(readme, /docs\/parallel-slices\/using-cursor\.md/);
    assert.match(readme, /docs\/parallel-slices\/using-claude-code\.md/);
    assert.match(readme, /Node\.js 22 LTS or 24 LTS/);
    assert.match(
      readme,
      /review provider only when multi-agent review is enabled/,
    );
    assert.match(
      readme,
      /Multi-agent planning and integrated slice\/code review is optional/,
    );
    assert.match(readme, /"enabled": false/);
    assert.ok(
      readme.indexOf('"enabled": false') <
        readme.indexOf("## Understand the complete workflow"),
    );
    assert.match(readme, /Docker Desktop/);
    assert.doesNotMatch(readme, /## What the workflow does/);
    assert.match(readme, /`apps\/web\/` is the starter Next\.js application/);
    assert.match(readme, /`docs\/` is the root for repository documentation/);
    assert.doesNotMatch(readme, /apps\/docs/);
    assert.match(readme, /npm ci/);
    assert.doesNotMatch(readme, /create-turbo@latest/);
    assert.deepEqual(verifyScaffoldProfile(root), {
      applications: ["apps/web"],
      status: "verified",
    });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("configures an external-API scaffold without database features", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-external-api-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    const profile = configureScaffold(root, {
      createTurboVersion: "2.10.5",
      dataLayer: "external-api-only",
      manager: "npm",
    });
    const readme = readFileSync(join(root, "README.md"), "utf8");
    assert.equal(profile.dataLayer, "external-api-only");
    assert.match(readme, /Architecture profile: `external-api-only`/);
    assert.match(
      readme,
      /external API integration without an application database/,
    );
    assert.doesNotMatch(readme, /SQL security/);
    assert.deepEqual(verifyScaffoldProfile(root, "external-api-only"), {
      applications: ["apps/web"],
      status: "verified",
    });
    writeFileSync(
      join(root, "package.json"),
      `${JSON.stringify(
        {
          ...JSON.parse(readFileSync(join(root, "package.json"), "utf8")),
          dependencies: { pg: "8.22.0" },
        },
        null,
        2,
      )}\n`,
    );
    assert.throws(
      () => inspectArchitecture(root, { profile: "external-api-only" }),
      /prohibits pg/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refuses an unreviewed generator dependency before changing files", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-unreviewed-dependency-"),
  );
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    const applicationPath = join(root, "apps/web/package.json");
    const application = JSON.parse(readFileSync(applicationPath, "utf8"));
    application.devDependencies["unreviewed-package"] = "1.0.0";
    writeFileSync(applicationPath, `${JSON.stringify(application, null, 2)}\n`);
    const rootBefore = readFileSync(join(root, "package.json"), "utf8");
    assert.throws(
      () =>
        configureScaffold(root, {
          createTurboVersion: "2.10.5",
          manager: "npm",
        }),
      /scaffold dependency baseline is missing unreviewed-package/,
    );
    assert.equal(readFileSync(join(root, "package.json"), "utf8"), rootBefore);
    application.devDependencies["unreviewed-package"] = "workspace:*";
    writeFileSync(applicationPath, `${JSON.stringify(application, null, 2)}\n`);
    assert.throws(
      () =>
        configureScaffold(root, {
          createTurboVersion: "2.10.5",
          manager: "npm",
        }),
      /uses workspace protocol without a local package/,
    );
    assert.equal(readFileSync(join(root, "package.json"), "utf8"), rootBefore);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("renders clone onboarding for every supported package manager", () => {
  const baseline = loadScaffoldBaseline();
  const expectedCommands = {
    npm: ["npm ci", "npm run build"],
    pnpm: [
      "corepack-runner.mjs pnpm install --frozen-lockfile",
      "corepack-runner.mjs pnpm run build",
    ],
    yarn: [
      "corepack-runner.mjs yarn install --immutable",
      "corepack-runner.mjs yarn run build",
    ],
    bun: ["bun install --frozen-lockfile", "bun run build"],
  };

  for (const [manager, commands] of Object.entries(expectedCommands)) {
    const root = mkdtempSync(
      join(tmpdir(), `parallel-slices-${manager}-readme-`),
    );
    try {
      writeScaffold(root, {
        foundationDependencies: false,
        manager,
        nextApps: true,
      });
      configureScaffold(root, {
        createTurboVersion: "2.10.5",
        manager,
      });
      const readme = readFileSync(join(root, "README.md"), "utf8");
      const rootPackage = JSON.parse(
        readFileSync(join(root, "package.json"), "utf8"),
      );
      for (const command of commands) assert.ok(readme.includes(command));
      assert.doesNotMatch(readme, /{{[A-Z_]+}}/);
      assert.equal(
        rootPackage.packageManager,
        `${manager}@${baseline.parallelSlices.packageManagers[manager]}`,
      );
      assert.equal(verifyScaffoldProfile(root).status, "verified");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }
});

test("generated Dependabot updates stay dormant until initialization", () => {
  const config = parseYaml(
    readFileSync(
      join(
        import.meta.dirname,
        "../architectures/nextjs-gcp-postgres/repo-overlay/.github/dependabot.yml",
      ),
      "utf8",
    ),
  );
  assert.deepEqual(
    config.updates.map((update) => update["package-ecosystem"]),
    ["npm", "github-actions"],
  );
  assert.ok(
    config.updates.every((update) => update["open-pull-requests-limit"] === 0),
  );
  assert.deepEqual(
    config.updates[0].ignore.map((entry) => entry["dependency-name"]).sort(),
    ["@eslint/js", "@types/node", "eslint", "typescript"],
  );
});

test("architecture inspection requires a Next.js Turborepo", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-architecture-shape-"),
  );
  try {
    writeScaffold(root);
    const packagePath = join(root, "package.json");
    const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
    delete manifest.devDependencies.next;
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    assert.throws(
      () => inspectArchitecture(root),
      /requires at least one Next\.js package/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("foundation verification requires exact PostgreSQL tooling", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-architecture-foundation-"),
  );
  try {
    writeScaffold(root, { dependencyUpdates: true, nextApps: true });
    assert.equal(
      inspectArchitecture(root, { foundationReady: true }).foundationReady,
      true,
    );
    const packagePath = join(root, "package.json");
    const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
    delete manifest.dependencies.pg;
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    assert.throws(
      () => inspectArchitecture(root, { foundationReady: true }),
      /must declare pg in dependencies/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("foundation verification refuses dormant routine dependency updates", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-dependabot-dormant-"),
  );
  try {
    writeScaffold(root, { dependencyUpdates: true, nextApps: true });
    const configPath = join(root, ".github/dependabot.yml");
    const config = readFileSync(configPath, "utf8").replace(
      "    directory: /\n",
      "    directory: /\n    open-pull-requests-limit: 0\n",
    );
    writeFileSync(configPath, config);
    assert.throws(
      () => inspectArchitecture(root, { foundationReady: true }),
      /initialization must enable routine Dependabot version updates/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refuses a symlinked generated README before changing the scaffold", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-readme-symlink-"));
  const outside = join(root, "outside.md");
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    writeFileSync(outside, "outside remains unchanged\n");
    symlinkSync(outside, join(root, "README.md"));
    const packageBefore = readFileSync(join(root, "package.json"), "utf8");

    assert.throws(
      () =>
        configureScaffold(root, {
          createTurboVersion: "2.10.5",
          manager: "npm",
        }),
      /refusing to replace symlinked scaffold file/,
    );
    assert.equal(readFileSync(outside, "utf8"), "outside remains unchanged\n");
    assert.equal(
      readFileSync(join(root, "package.json"), "utf8"),
      packageBefore,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refuses a symlinked upstream docs application before changing the scaffold", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-docs-symlink-"));
  const outside = mkdtempSync(join(tmpdir(), "parallel-slices-docs-outside-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    rmSync(join(root, "apps/docs"), { recursive: true });
    writeFileSync(join(outside, "marker.txt"), "outside remains unchanged\n");
    symlinkSync(outside, join(root, "apps/docs"), "dir");
    const packageBefore = readFileSync(join(root, "package.json"), "utf8");

    assert.throws(
      () =>
        configureScaffold(root, {
          createTurboVersion: "2.10.5",
          manager: "npm",
        }),
      /refusing to remove symlinked upstream documentation application/,
    );
    assert.equal(
      readFileSync(join(outside, "marker.txt"), "utf8"),
      "outside remains unchanged\n",
    );
    assert.equal(
      readFileSync(join(root, "package.json"), "utf8"),
      packageBefore,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
    rmSync(outside, { recursive: true, force: true });
  }
});

test("generated scaffold verification rejects missing canonical documentation", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-readme-documentation-"),
  );
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const readmePath = join(root, "README.md");
    const readme = readFileSync(readmePath, "utf8").replace(
      "github.com/jtrefry/parallel-slices/blob/main/docs/mechanism-map.md",
      "example.com/missing-mechanism-map",
    );
    writeFileSync(readmePath, readme);

    assert.throws(
      () => verifyScaffoldProfile(root),
      /generated README\.md must preserve canonical mechanism documentation/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated scaffold verification keeps the review default near the top", () => {
  const root = mkdtempSync(
    join(tmpdir(), "parallel-slices-readme-review-default-"),
  );
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const readmePath = join(root, "README.md");
    const reviewDefault = `\`\`\`json
{
  "enabled": false,
  "reviewers": []
}
\`\`\`
`;
    const readme = readFileSync(readmePath, "utf8")
      .replace(reviewDefault, "")
      .replace("## Prerequisites", `${reviewDefault}\n## Prerequisites`);
    writeFileSync(readmePath, readme);

    assert.throws(
      () => verifyScaffoldProfile(root),
      /must show the multi-agent review default before the workflow guide/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated scaffold verification rejects framework drift", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-next-drift-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const packagePath = join(root, "apps/web/package.json");
    const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
    manifest.dependencies.next = "0.0.0";
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    assert.throws(
      () => verifyScaffoldProfile(root),
      /must declare next@.*found 0\.0\.0/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated scaffold verification rejects Node.js runtime drift", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-node-drift-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const packagePath = join(root, "package.json");
    const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
    const expectedRange = manifest.engines.node;
    manifest.engines.node = ">=18";
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    assert.throws(
      () => verifyScaffoldProfile(root),
      /package\.json must declare Node\.js engines/,
    );

    manifest.engines.node = expectedRange;
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    writeFileSync(join(root, ".node-version"), "22\n");
    assert.throws(
      () => verifyScaffoldProfile(root),
      /\.node-version must pin Node\.js 24/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated scaffold verification rejects the legacy apps/docs profile", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-docs-profile-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const profilePath = join(root, ".parallel-slices/scaffold-profile.json");
    const profile = JSON.parse(readFileSync(profilePath, "utf8"));
    profile.applications = ["apps/docs", "apps/web"];
    writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);

    assert.throws(
      () => verifyScaffoldProfile(root),
      /scaffold profile must list only apps\/web/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("generated scaffold verification rejects Tailwind reintroduction", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-tailwind-drift-"));
  try {
    writeScaffold(root, {
      foundationDependencies: false,
      nextApps: true,
    });
    configureScaffold(root, {
      createTurboVersion: "2.10.5",
      manager: "npm",
    });
    const packagePath = join(root, "apps/web/package.json");
    const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
    manifest.devDependencies.tailwindcss = "4.0.0";
    writeFileSync(packagePath, `${JSON.stringify(manifest, null, 2)}\n`);
    assert.throws(
      () => verifyScaffoldProfile(root),
      /Tailwind dependency is prohibited/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("existing repositories without a generated profile remain technology-neutral", () => {
  const root = mkdtempSync(join(tmpdir(), "parallel-slices-adoption-ui-"));
  try {
    writeScaffold(root);
    assert.equal(readScaffoldProfile(root), null);
    assert.deepEqual(verifyScaffoldProfile(root), { status: "not-generated" });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
